[tool.poetry]
name = "eptic"
version = "0.1.0"
description = ""
authors = ["ffedox <test@test.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.5"
seaborn = "^0.13.0"
hydra-core = "^1.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
