import sys
import pandas as pd
import re
from Levenshtein import distance as levenshtein_distance

# Adjusting the sys.path to be able to import the modules from different directories
sys.path.append(r"E:\Code\eptic\src\skeptic")
sys.path.append(r"E:\Code\eptic\src\noske")

# Importing the extract_columns module
import extract_clean_texts_skeptic
# Importing the extract_texts_clean module
import extract_clean_texts_noske

def clean_text(text):
    # Replace double whitespaces with single whitespace
    text = re.sub(r'\s+', ' ', text)
    return text.strip()  # This removes any leading or trailing whitespace

def main():
    # Run the extract_columns module
    extract_clean_texts_skeptic.main()
    
    # Run the extract_texts_clean module
    extract_clean_texts_noske.main()

    # Load the Excel file generated by extract_texts_clean
    df_cleaned_texts = pd.read_excel("clean_texts_noske.xlsx")
    
    # Store original texts in a new column before cleaning
    df_cleaned_texts['original_text'] = df_cleaned_texts['s.text_processed']
    
    # Clean the texts from df_cleaned_texts
    df_cleaned_texts['cleaned_text'] = df_cleaned_texts['s.text_processed'].apply(clean_text)

    # Load the Excel file generated by extract_columns
    df_texts = pd.read_excel("clean_texts_skeptic.xlsx")
    
    # Store original texts in a new column before cleaning
    df_texts['original_text'] = df_texts['plain_text']
    
    # Clean the texts
    df_texts['cleaned_text'] = df_texts['plain_text'].apply(clean_text)
    
    # Initialize columns to store the Levenshtein Distance and the matching text ID
    df_cleaned_texts['levenshtein_distance'] = None
    df_cleaned_texts['matching_text_id'] = None
    df_cleaned_texts['matching_text'] = None  # New column for storing the matching text

    # For each text in df_cleaned_texts
    for index, row in df_cleaned_texts.iterrows():
        # Text for comparison from the current row
        current_text = row['cleaned_text']
        spoken_written = row['spoken_written']
        source_target = row['source_target']

        # Filter texts by spoken_written and source_target
        filtered_texts = df_texts[(df_texts['spoken_written'] == spoken_written) & (df_texts['source_target'] == source_target)]
        
        # Initialize variables to store the results
        min_distance = float('inf')
        matching_text_id = None
        matching_event_id = None
        matching_text = None  # Variable for the matching text
        
        # Compare with each text in df_texts
        for idx, text_row in filtered_texts.iterrows():
            # Text for comparison
            comparison_text = text_row['cleaned_text']
            
            # Calculate Levenshtein distance
            dist = levenshtein_distance(current_text, comparison_text)
            
            # Check if this distance is the smallest we've seen so far
            if dist < min_distance:
                min_distance = dist
                matching_text_id = text_row['id']
                matching_event_id = text_row['event_id']
                matching_text = text_row['original_text']  # Store the original text that matches
        
        # Assign the results to the DataFrame
        df_cleaned_texts.at[index, 'levenshtein_distance'] = min_distance
        df_cleaned_texts.at[index, 'matching_text_id'] = matching_text_id
        df_cleaned_texts.at[index, 'matching_event_id'] = matching_event_id
        df_cleaned_texts.at[index, 'matching_text'] = matching_text  # Assign the matching text

    # Save DataFrame to Excel file
    df_cleaned_texts.to_excel('levenshtein_distance_noske.xlsx', index=False, engine='openpyxl')

    print("Results saved to levenshtein_distance_noske.xlsx")

if __name__ == "__main__":
    main()