hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data:
  raw: data/raw/sample.csv
  processed: data/processed/processed.csv
  final: data/final/final.csv

db:
  credentials: ../config.json

paths:
  tests: C:/Users/Alice/Desktop/Code/eptic/tests
  src: C:/Users/Alice/Desktop/Code/eptic/src