hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data:
  raw: data/raw/sample.csv
  processed: data/processed/processed.csv
  final: data/final/final.csv

db:
  credentials: E:\Code\eptic\config.json

noskeptic:
  credentials: E:\Code\eptic\config_noskeptic.json

paths:
  tests: E:\Code\eptic\tests
  src: E:\Code\eptic\src

outputs:
  graphs: E:\Code\eptic\docs